### PR TITLE
support event stream

### PR DESCRIPTION
**Pull request by lexdene**
usage:

    for event in client.events.watch(
        types=['Notification'],
        queue='my_queue',
    ):
        do_something_with(event)

### CODE REVIEW

**Comment by lexdene** [comment]
@tclh123 pls review and merge.

**Comment by tclh123** [comment]
@lexdene Thanks!
Could you update the usage section in `README.md`? That would be helpful.

**Comment by lexdene** [comment]
done

**Comment by lexdene** [comment]
Would you please upload it onto pypi so that I can pip install it on production env?

**Comment by tclh123** [comment]
@lexdene uploaded https://pypi.org/project/icinga2py/0.1.2/

**Comment by lexdene** [comment]
Thank you!

**Pull request merged**
